# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-24 02:04
from __future__ import unicode_literals

import datetime
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='\u5de5\u53f7')),
                ('fullname', models.CharField(max_length=10, verbose_name='\u59d3\u540d')),
                ('group', models.IntegerField(choices=[(1, '\u7814\u53d1\u4e00\u7ec4'), (2, '\u7814\u53d1\u4e8c\u7ec4'), (3, '\u7814\u53d1\u4e09\u7ec4')], default=1, verbose_name='\u7814\u53d1\u7ec4')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True)),
                ('uploader', models.CharField(blank=True, max_length=30, null=True)),
                ('des', models.CharField(blank=True, max_length=80, null=True)),
                ('up_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u540d\u79f0',
                'verbose_name_plural': '\u6587\u4ef6\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, max_length=80, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=30, null=True)),
                ('des', models.CharField(blank=True, max_length=80, null=True)),
                ('make_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9879\u76ee\u540d\u79f0',
                'verbose_name_plural': '\u9879\u76ee\u540d\u79f0',
            },
        ),
        migrations.AddField(
            model_name='files',
            name='program_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mng_sys.Programs'),
        ),
    ]
